---
- name: Copy "docker" application folder across
  copy:
    src: "{{ playbook_dir }}/../docker/"
    dest: "{{ docker_remote_app_dir }}"
  tags:
    - app

- name: test docker-compose
  docker_compose:
    project_src: "{{ docker_remote_app_dir }}"
    state: present
  tags:
    - app
