---
# This playbook sets up whole stack.
  
- name: Configurations to "remote" host
  hosts: web_servers
  become: yes
  roles:
    - setup
  
- name: Copying "docker" application folder on remote server
  hosts: web_servers
  become: yes
  roles:
    - app
